---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-172-17-0-2
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /opt/quayregistry
    server: 172.17.0.2
