---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-172-31-31-44
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /exports
    server: 172.31.31.44
